Repository landlab/landlab, pull requests merged in 2023-10, with the labels that each got.

#1774 Bump dependencies
  .github/workflows/changelog.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/prerelease.yml
  .github/workflows/rebase_dependencies.yml
  .github/workflows/release.yml
  .github/workflows/test-notebooks.yml
  .github/workflows/test.yml
  docs/requirements.txt
  notebooks/requirements.txt
  requirements.txt
Labels: skip news

#1650 BedrockLandslider: Add getters for several input parameters.
  landlab/components/bedrock_landslider/bedrock_landslider.py
  news/1651.misc
Labels: v2.7

#1743 OverlandFlow: add support for spatially non-uniform rainfall
  landlab/components/overland_flow/generate_overland_flow_deAlmeida.py
  news/1743.feature
  tests/components/overland_flow/test_dealmeida_overland_flow.py
Labels: enhancement, v2.7

#1649 SpaceLargeScaleEroder: Add getter for several input parameters.
  landlab/components/space/space_large_scale_eroder.py
  news/1652.misc
  tests/components/space/test_space_large_scale_eroder.py
Labels: v2.7

#1268 use length_of_link or length_of_d8 as appropriate; add test; modify i…
  landlab/components/drainage_density/drainage_density.py
  news/1266.bugfix
  tests/components/drainage_density/test_drainage_density.py
Labels: v2.7

#1640 Keep sediment__influx values in SpaceLargeScaleEroder
  landlab/components/space/ext/calc_sequential_ero_depo.pyx
  landlab/components/space/space_large_scale_eroder.py
  news/1638.bugfix
  tests/components/space/test_space_large_scale_eroder.py
Labels: v2.7

#1790 Bump dependencies
  requirements/docs.txt
  requirements/notebooks.txt
  requirements/required.txt
Labels: skip news
